### ISSUE TITLE
cmd中运行异常

### ISSUE THREAD

**Issue by 1640407560** [wux1an/wxapkg#9]
您好，我打开小程序后，在微信默认的路径上cmd，然后执行wxapkg.exe scan 黑窗口会直接卡消失，这是神马情况

**Comment by wux1an** [comment]
windows 系统版本是多少，`scan` 子命令用了 tui 库，有可能不兼容。可以用 `wxapkg.exe unpack` 命令，指定小程序路径直接解包。

**Comment by 1640407560** [comment]
windows10的

**Comment by 1640407560** [comment]
大佬，程序中有需要修改的地方没，

**Comment by 1640407560** [comment]
用这个指令   wxapkg  unpack  这个指令
![image](https://github.com/wux1an/wxapkg/assets/143772156/e4793950-950d-4e99-9ea0-348121d49982)
出现了这个错误
